server:
  servlet:
    context-path: /empsys

mybatis:
  type-aliases-package: com.li.day08_springboot_emp.entity
  mapper-locations: classpath:mapping/*.xml

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/empsys?serverTimezone=Asia/Shanghai
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      max-active: 20
      initial-size: 5

  thymeleaf:
    #缓存为false
    cache: false
#不显示thymeleaf的日志
logging:
  level:
    org:
      thymeleaf=info: